### ISSUE TITLE
Some letters do not show correctly

### ISSUE THREAD

**Issue by beikimajid** [shahabbai/Persian_Plate_Recognition#5]
Hello, thank you for your project. Some letters, including the letter "ج" and "ل", do not show correctly. I will send you a sample. At what angle can he read the license plate?
![G](https://github.com/shahabbai/Persian_Plate_Recognition/assets/3895372/872dba86-090b-4573-90d8-ffbdfbe2c660)

**Comment by shahabbai** [comment]
Hello. Do you have any other samples to test those letters more?
